apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: spiffe-spire
  namespace: metallb-system
spec:
  addresses:
    - 172.19.255.1-172.19.255.10
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
