---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-service-account
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: broker-webapp
  labels:
    app: broker-webapp
    nsm/role: client
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
      name: http
  selector:
    app: broker-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-webapp
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-webapp
      version: v1
  template:
    metadata:
      labels:
        app: broker-webapp
        version: v1
    spec:
      serviceAccount: client-service-account
      containers:
        - name: webapp
          image: ghcr.io/nishantapatil3/spire-federation-kind/broker-webapp:latest
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUOTES_SERVICE_HOST
              value: "stock-quotes-service" # Use Kubernetes service name instead of IP
          volumeMounts:
            - mountPath: /run/spire/sockets
              name: spire-agent-socket
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
