name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make build

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push broker-webapp
      uses: docker/build-push-action@v3
      with:
        context: ./src/broker-webapp
        file: ./src/broker-webapp/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/broker-webapp:latest

    - name: Build and push stock-quotes-service
      uses: docker/build-push-action@v3
      with:
        context: ./src/stock-quotes-service
        file: ./src/stock-quotes-service/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/stock-quotes-service:latest
